### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by Zeromatiker** [chozabu/LinNetLim#3]
Installation guide is missing some steps: 
first: `sudo apt install virtualenv`
then `pip install -r requirements.txt` threw some error that Cython is missing, `pip install Cython` helped

second try of `pip install -r requirements.txt`:

    Complete output from command python setup.py egg_info:
    Found pcap headers in /usr/src/linux-headers-4.10.0-20-generic/include/config/input/pcap.h
    Found libraries in None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oEuHhY/pypcap/setup.py", line 63, in <module>
        lib_file = os.path.basename(lib_file_path)
      File "/blablabla/LinNetLim-master/env/lib/python2.7/posixpath.py", line 114, in basename
        i = p.rfind('/') + 1
    AttributeError: 'NoneType' object has no attribute 'rfind'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oEuHhY/pypcap/

When running `sudo env/bin/python kivy_ui.py`:

    Traceback (most recent call last):
      File "kivy_ui.py", line 2, in <module>
        from kivy.app import App
    ImportError: No module named kivy.app

sorry if its my fault somehow.

**Comment by partytoni** [comment]
i got the same error.

**Comment by chozabu** [comment]
Hey, not sure what the issue here is, but are you on py2 or py3? there is a req file for each

**Comment by partytoni** [comment]
I am on py3. But i tried both for being sure. Actually i was able to
install cython using apt-get and the installation was succesful. The
problem is in the requirements i guess, im not a pro user, sorry :)

Il 20 giu 2017 02:41, "Alex P-B" <notifications@github.com> ha scritto:
