### ISSUE TITLE
Same issue as others

### ISSUE THREAD

**Issue by KIMWW** [chozabu/LinNetLim#4]
First, I want to thank you for having created this program similar to NetLimiter which I was using quite regularly with Windows.

So, I have the same issue as others:
When I run: `pip install -r requirements.txt` I get:

> Complete output from command python setup.py egg_info:
>     Found pcap headers in /usr/src/linux-headers-4.4.0-53-generic/include/config/ezx/pcap.h
>     Found libraries in None
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-zaTcFw/pypcap/setup.py", line 63, in <module>
>         lib_file = os.path.basename(lib_file_path)
>       File "/ME/Downloads/LinNetLim-master/env/lib/python2.7/posixpath.py", line 114, in basename
>         i = p.rfind('/') + 1
>     AttributeError: 'NoneType' object has no attribute 'rfind'

I tried on py3, py2.7 and of course py2, but same problem.

I am looking forward to use it when it will be installed so I really hope you got news to resolve this problem??

**Comment by chozabu** [comment]
OK, I can't replicate the issue, but had a google around and found: https://github.com/dugsong/pypcap/issues/49

where f0ol mentions: "Pip is using the wrong pcap header. Install libpcap-dev will fix this issue in ubuntu."

so hopefully this can be fixed by

sudo apt install libpcap-dev

I'll add this to the readme - thanks for the report.

Also, trying out linnetlim - It seems there is an issue with downstream limiting, I may disable this part until I or someone else has the time to fix it properly.

**Comment by chozabu** [comment]
OK! both of those small tasks are done - do let me know if the system runs OK with the updated readme

**Comment by KIMWW** [comment]
Thanks for replying.
It's getting further but failed.
1st I got:
>    #error Do not use this file, it is the result of a failed Cython compilation.

Because when running `pip install Cython` the latest version which was installed it's 0.26 but it's not compatible with Kivy 1.9.1. Only Cython 0.23 is compatible with the 1.9.1 version. So I run `pip install Cython==0.23` but now I am getting:

> In file included from /tmp/pip-build-Tyh8bh/Kivy/kivy/graphics/opengl.c:242:0:
    /tmp/pip-build-Tyh8bh/Kivy/kivy/graphics/gl_redirect.h:43:22: fatal error: GL/gl.h: No such file or directory

I am stuck here.

I did many searches on Internet and the only thing I found is: 
[https://stackoverflow.com/questions/40088622/linux-unable-to-install-kivy-in-virtual-environment/40089362](url) and [https://kivy.org/docs/installation/installation-linux.html#using-software-packages](url).
The problem seems to be with OpenGL but I don't know what to do...
